from typing import List, Dict, Any

EMPLOYEES: List[Dict[str, Any]] = [
    {
        "id": 1,
        "first_name": "Aarav",
        "last_name": "Sharma",
        "email": "aarav.sharma@company.com",
        "phone": "+91-9876543210",
        "department": "Engineering",
        "designation": "Senior Software Engineer",
        "status": "Active",
        "date_of_joining": "2021-03-15",
        "salary": 95000,
        "avatar": "https://api.dicebear.com/7.x/avataaars/svg?seed=Aarav",
    },
    {
        "id": 2,
        "first_name": "Priya",
        "last_name": "Patel",
        "email": "priya.patel@company.com",
        "phone": "+91-9876543211",
        "department": "Human Resources",
        "designation": "HR Manager",
        "status": "Active",
        "date_of_joining": "2020-07-01",
        "salary": 80000,
        "avatar": "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    },
    {
        "id": 3,
        "first_name": "Rohan",
        "last_name": "Mehta",
        "email": "rohan.mehta@company.com",
        "phone": "+91-9876543212",
        "department": "Finance",
        "designation": "Financial Analyst",
        "status": "Active",
        "date_of_joining": "2022-01-10",
        "salary": 72000,
        "avatar": "https://api.dicebear.com/7.x/avataaars/svg?seed=Rohan",
    },
    {
        "id": 4,
        "first_name": "Sneha",
        "last_name": "Reddy",
        "email": "sneha.reddy@company.com",
        "phone": "+91-9876543213",
        "department": "Marketing",
        "designation": "Marketing Specialist",
        "status": "On Leave",
        "date_of_joining": "2021-09-20",
        "salary": 68000,
        "avatar": "https://api.dicebear.com/7.x/avataaars/svg?seed=Sneha",
    },
    {
        "id": 5,
        "first_name": "Karan",
        "last_name": "Singh",
        "email": "karan.singh@company.com",
        "phone": "+91-9876543214",
        "department": "Engineering",
        "designation": "DevOps Engineer",
        "status": "Active",
        "date_of_joining": "2020-11-05",
        "salary": 90000,
        "avatar": "https://api.dicebear.com/7.x/avataaars/svg?seed=Karan",
    },
    {
        "id": 6,
        "first_name": "Divya",
        "last_name": "Nair",
        "email": "divya.nair@company.com",
        "phone": "+91-9876543215",
        "department": "Design",
        "designation": "UI/UX Designer",
        "status": "Active",
        "date_of_joining": "2022-06-15",
        "salary": 75000,
        "avatar": "https://api.dicebear.com/7.x/avataaars/svg?seed=Divya",
    },
    {
        "id": 7,
        "first_name": "Vikram",
        "last_name": "Joshi",
        "email": "vikram.joshi@company.com",
        "phone": "+91-9876543216",
        "department": "Engineering",
        "designation": "Backend Developer",
        "status": "Inactive",
        "date_of_joining": "2019-04-22",
        "salary": 85000,
        "avatar": "https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram",
    },
    {
        "id": 8,
        "first_name": "Anjali",
        "last_name": "Verma",
        "email": "anjali.verma@company.com",
        "phone": "+91-9876543217",
        "department": "Sales",
        "designation": "Sales Executive",
        "status": "Active",
        "date_of_joining": "2023-02-01",
        "salary": 60000,
        "avatar": "https://api.dicebear.com/7.x/avataaars/svg?seed=Anjali",
    },
]
